### ISSUE TITLE
The package stream-fusion is not compatible with the newest ghc

### ISSUE THREAD

**Issue by x-ji** [nionita/Barbarossa#1]
It seems that there is some change in ghc 7.10 that broke the package stream-fusion. Now `cabal install` throws an error:

```
[3 of 3] Compiling Control.Monad.Stream ( Control/Monad/Stream.hs, dist/dist-sandbox-8bb5b9c9/build/Control/Monad/Stream.o )

Control/Monad/Stream.hs:136:10:
    Ambiguous occurrence ‘MonadPlus’
    It could refer to either ‘Control.Monad.Stream.MonadPlus’,
                            defined at Control/Monad/Stream.hs:124:1
                          or ‘GHC.Base.MonadPlus’,
                            imported from ‘GHC.Base’ at Control/Monad/Stream.hs:80:1-15

Control/Monad/Stream.hs:140:10:
    Ambiguous occurrence ‘MonadPlus’
    It could refer to either ‘Control.Monad.Stream.MonadPlus’,
                            defined at Control/Monad/Stream.hs:124:1
                          or ‘GHC.Base.MonadPlus’,
                          imported from ‘GHC.Base’ at Control/Monad/Stream.hs:80:1-15
```

At https://stackoverflow.com/questions/33562781/cannot-install-haskell-package-stream-fusion-0-1-2-5-ambiguous-occurence somebody provided a solution of replacing `Data.List.Stream` with `Data.List` and removing `stream-fusion`, but it will certainly impact the program.

I emailed the maintainer of `stream-fusion` but got no reply.

**Comment by nionita** [comment]
Version 0.4.0, which is now in preparation and will be released hopefully sometime in July this year, does not depend on strea,-fusion anymore. Until version 0.3.0 inclusive please compile with older Hackage versions.
