### ISSUE TITLE
package "old-time" is deprecated for a good reason.

### ISSUE THREAD

**Issue by ruffianeo** [nionita/Barbarossa#3]
Data.Time is the current alternative as recommended in hackage old-time documentation.
The problem with old-time is that it is not compiling on windows (unless you install funny stuff like cygwin/gcc or alike).

**Comment by nionita** [comment]
Yes, this part was not touched for a long time, I will use the new library for next release.
Thanks for pointing this out, I did not know that there are problems on Windows with the old library, as I develop it mainly on Windows and just test on Linux.
